<h1> What is Machine Learning </h1>

- Machine Learning is a method of data analysis that automates analytical model building
- Using algorithms that iteratively learn form data, machine learning allows computers to find hidden insights without being explicitly programmed where to look.

<h2> What is it used for? </h2>

- Fraud detection
- Web search results
- Real-time ads on web pages
- Credit scoring and text-best offers
- Prediction of equipment failures
- New pricing models
- Network intrusion detection
- Recommendation Engines
- Customer Segmentation
- Text Sentiment Analysis
- Predicting Customer Churn
- Pattern and Image recognition
- Email spam filtering
- Financial Modeling
---
---

<h2> Machine Learning Process</h2>

<img src="ML process.png" />

<h3> There are 3 main types of Machine Learning algorithms</h3>

- Supervised Learning
- Unsupervised Learning
- Reinforcement Learning

<h4> Supervised Learning </h4>
    
- You have labeled data and are trying to perdict a label based off of known features<br>
<h4> Unsupervised Learning </h4>
    
- You have unlabeled data and are trying to group together similar data points based off of features <br>
<h4> Reinforcement Learning</h4>
    
- Algorithms learns to perform an action from experence
    
---
---

<h3> Supervised Learning </h3>

- Through methods like classification, regression, prediction and gradient boostin, supervised learning uses patters to predict the values of the label on additional unlabeled data.
- Supervised learning is commonly used in applications where historical data predicts likely future events.


- For example , it can anticipate when credit card transactions are likely to be fraudulent or which insurance customer is likely to file a claim.
- Or it can attempt to predict the price of a house based on different features for houses for which we have historical price data.

---

<h3> Supervised Learning </h3>

- Unsupervised learning is used against data that has no historical labels.
- The system is not told the "right answer". The algorithm must figure out what is being show.
- The goal is to explore the data and find some structure within.

- Or it can find the main attributes that separate customer segments frome each other.
- Popular techniques include self-organizing maps, nearest-neighbor mapping, k-means clustering and singular value decomposition.
- These algorithms are also used to segment text topics, recommend items and identify data outliers.

foo <font color='blue'>bar</font> foo

- <font color="green">These algorithms are also used to segment text topics, recommend items and identify data outliers.</font>

---
---

<h3> Reinforcement Learning </h3>

- Is often used for robotics, gaming and navigation.
- With reinforcement learning, the algorithm discovers through trial and error which actions yield the greatest rewards.


- This type of learning has three primary components: The agent(the learner or decision maker), the environment (everythin the agent interacts with) and actions (what the agent can do)
- The objective is for the agent to choose actions that maximize the expected reward over a given amount of time.

- The goal in inforcement learning is to learn the best policy.

<h4> We will be using the scikit learn package.</h4>

You'll need to install it using;<br>

```conda install scikit-learn```<br>
or<br>
```pip install scikit-learn```


In [2]:
import sklearn

In [3]:
from sklearn.linear_model import LinearRegression

<b><font color="red"> Estimator parameters </font> All the parameters of an estimator can be set when it is instantiated, and have suitable default values.</b>

In [4]:
model = LinearRegression(normalize=True)

In [5]:
print(model)

LinearRegression(normalize=True)


In [6]:
from sklearn.model_selection import train_test_split

In [7]:
import numpy as np


In [8]:
X = np.arange(10).reshape((5,2))

In [9]:
y = range(5)

In [10]:
list(y)

[0, 1, 2, 3, 4]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True)

In [14]:
X_train

array([[6, 7],
       [2, 3],
       [0, 1]])

In [15]:
y_test

[2, 4]

In [16]:
y_train

[3, 1, 0]

In [17]:
X_test

array([[4, 5],
       [8, 9]])

In [18]:
model.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(


LinearRegression(normalize=True)

In [19]:
predictions = model.predict(X_test)

In [20]:
predictions

array([2., 4.])

In [21]:
y_test

[2, 4]

In [23]:
model.score(X,y)

1.0