<h1> Numpy </h1>

- Numpy is a Linear Algebra Library for python, the reason it is so important
for Data Science with Python is that almost all of the libraries in the PyData
Ecosystem rely on Numpy as one of their main building blocks
- Numpy is also incredibly fast, as it has bindings to C libraries.
---

- if you have Anaconda, install Numpy by going to your terminal
or command prompt and typing:<br><br>
    ```conda install numpy```<br>
    ```pip install numpy```
    
---

- Numpy arrays essentially come in two flavors:
    1. vectors 1-d arrays
    2. matrices 2-d arrays

<h2> Numpy Arrays </h2>

In [59]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
type(my_list)

list

In [4]:
import numpy as np

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.ndim

1

In [10]:
arr.shape

(3,)

In [11]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.array(my_mat).shape

(3, 3)

In [16]:
np.arange(2, 300, 5, dtype=np.float32)

array([  2.,   7.,  12.,  17.,  22.,  27.,  32.,  37.,  42.,  47.,  52.,
        57.,  62.,  67.,  72.,  77.,  82.,  87.,  92.,  97., 102., 107.,
       112., 117., 122., 127., 132., 137., 142., 147., 152., 157., 162.,
       167., 172., 177., 182., 187., 192., 197., 202., 207., 212., 217.,
       222., 227., 232., 237., 242., 247., 252., 257., 262., 267., 272.,
       277., 282., 287., 292., 297.], dtype=float32)

In [17]:
arrg = np.arange(2, 300, 5, dtype=np.float32)

In [18]:
arrg.shape

(60,)

In [19]:
arrg.ndim

1

In [22]:
arrg.reshape(20,3).shape

(20, 3)

In [23]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.zeros_like(5)

array(0)

In [28]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones(4)

array([1., 1., 1., 1.])

In [33]:
np.ones((5,3), dtype=np.float32).dtype

dtype('float32')

In [31]:
np.ones((2,3)).dtype

dtype('float64')

In [34]:
np.linspace(2,67,100)

array([ 2.        ,  2.65656566,  3.31313131,  3.96969697,  4.62626263,
        5.28282828,  5.93939394,  6.5959596 ,  7.25252525,  7.90909091,
        8.56565657,  9.22222222,  9.87878788, 10.53535354, 11.19191919,
       11.84848485, 12.50505051, 13.16161616, 13.81818182, 14.47474747,
       15.13131313, 15.78787879, 16.44444444, 17.1010101 , 17.75757576,
       18.41414141, 19.07070707, 19.72727273, 20.38383838, 21.04040404,
       21.6969697 , 22.35353535, 23.01010101, 23.66666667, 24.32323232,
       24.97979798, 25.63636364, 26.29292929, 26.94949495, 27.60606061,
       28.26262626, 28.91919192, 29.57575758, 30.23232323, 30.88888889,
       31.54545455, 32.2020202 , 32.85858586, 33.51515152, 34.17171717,
       34.82828283, 35.48484848, 36.14141414, 36.7979798 , 37.45454545,
       38.11111111, 38.76767677, 39.42424242, 40.08080808, 40.73737374,
       41.39393939, 42.05050505, 42.70707071, 43.36363636, 44.02020202,
       44.67676768, 45.33333333, 45.98989899, 46.64646465, 47.30

In [35]:
# Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.random.rand(5)

array([0.84624279, 0.31337855, 0.57638833, 0.14445356, 0.34653055])

In [37]:
np.random.rand(3,6)

array([[0.67965427, 0.40107039, 0.92484389, 0.29861746, 0.69812107,
        0.76571191],
       [0.71779258, 0.38434405, 0.58662598, 0.39371062, 0.48303811,
        0.65050245],
       [0.71634247, 0.04762536, 0.85335878, 0.72273944, 0.89118503,
        0.99212578]])

In [38]:
np.random.randn(2)

array([-1.0529771 , -1.32423024])

In [39]:
np.random.randn(3,5)

array([[ 0.02082344, -1.32812068, -0.65993589,  1.88404793, -0.59260118],
       [ 0.17505599,  0.12213925,  0.41528346,  1.0553739 ,  0.97945667],
       [ 0.87068679,  0.08707368, -1.07028375, -0.25294414,  0.932888  ]])

In [40]:
np.random.randint(1,100)

37

In [41]:
np.random.randint(1,200, 20)

array([182, 193, 164, 148, 128, 152, 197, 187, 114,  69, 111, 130, 179,
        10,  41, 125,  68,  14, 119,  99])

In [42]:
arr = np.arange(25)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
ranarr = np.random.randint(0,50,10)

In [45]:
ranarr

array([47, 12, 28, 14, 45, 16, 22, 45, 29, 13])

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
ranarr

array([47, 12, 28, 14, 45, 16, 22, 45, 29, 13])

In [48]:
ranarr.max()

47

In [49]:
ranarr.min()

12

In [50]:
ranarr

array([47, 12, 28, 14, 45, 16, 22, 45, 29, 13])

In [51]:
ranarr.argmax()

0

In [52]:
ranarr.argmin()

1

In [53]:
arr.shape

(25,)

In [54]:
arr.reshape(5,5).shape

(5, 5)

In [55]:
arr.dtype

dtype('int32')

In [57]:
 from numpy.random import randint

In [58]:
randint(2,80)

31

<h2> Numpy Indexing and Selection </h2>

In [60]:
 arr = np.arange(0,11)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr[8]

8

In [63]:
arr[1:5]

array([1, 2, 3, 4])

In [64]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [67]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

<h5> BroadCasting </h5>

In [68]:
arr[0:5] = 100

In [69]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [70]:
arr = np.arange(0,11)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
slice_of_arr = arr[0:6]

In [73]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [76]:
 slice_of_arr[:] = 99

In [77]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [78]:
arr_copy = arr.copy()

In [79]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [80]:
arr_copy[:] = 34

In [81]:
arr_copy

array([34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34])

In [82]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [83]:
arr_copy1 = arr_copy[:5].copy()

In [84]:
arr_copy1

array([34, 34, 34, 34, 34])

In [85]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [86]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [87]:
arr_2d[0][0]

5

In [88]:
arr_2d[1][1]

25

In [89]:
arr_2d[2][1]

40

In [90]:
arr_2d[2,1] # == arr_2d[2][1]

40

In [91]:
arr_2d[1,2] # == arr_2d[1][2]

30

In [92]:
arr_2d[0:2, 1:]

array([[10, 15],
       [25, 30]])

In [93]:
arr_2d[1:, ]

array([[20, 25, 30],
       [35, 40, 45]])

In [94]:
arr_2d[1:][:]

array([[20, 25, 30],
       [35, 40, 45]])

<h4> Conditional Selection </h4>

In [95]:
arr = np.arange(1,11)

In [96]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [98]:
bool_arr = arr > 5

In [99]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [100]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [101]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [103]:
arr[arr<3]

array([1, 2])

In [104]:
arr_2d = np.arange(50).reshape(5,10)

In [105]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [106]:
arr_2d[arr_2d%5==0]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [107]:
arr_2d.size

50

In [108]:
len(arr_2d)

5

In [109]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

array([], shape=(0, 10), dtype=int32)

<h2> Numpy Operations </h2>

- Array with Array
- Array with Scalars
- Universal Array Functions

In [114]:
arr = np.arange(0,11)

In [115]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [117]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [118]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [119]:
arr / arr

C:\Users\IT Center\AppData\Local\Temp\ipykernel_3148\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [120]:
arr + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [121]:
arr * 10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [122]:
arr -100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [123]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
arr/arr

C:\Users\IT Center\AppData\Local\Temp\ipykernel_3148\1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [125]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [126]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [127]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [128]:
np.max(arr)

10

In [129]:
np.min(arr)

0

In [130]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [131]:
np.log(arr)

C:\Users\IT Center\AppData\Local\Temp\ipykernel_3148\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [ ]:
map()